pages/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('home',views.home,name='home'),
    path('contact',views.contact,name='contact'),
    path('about',views.about,name='about'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('checklogin',views.checklogin,name='checklogin'),
    path('logout',views.logout,name='logout'),
    path('addtrainee',views.addtrainee,name='addtrainee'),
    path('addtrack',views.addtrack,name='addtrack'),
    path('index',views.index,name='index'),
    path('track111',views.track111,name='track111'),
    path('update/<int:id>',views.update,name='update'),
    path('actupdate/<int:id>',views.actupdate,name='actupdate'),
    path('dell/<int:id>',views.dell,name='dell')
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from pages.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('register',register,name='register'),
    path('',include("django.contrib.auth.urls")),
    

]

pages/models.py
from django.db import models

# Create your models here.
class myuser(models.Model):
    id=models.AutoField(primary_key=True)
    
    password=models.CharField(max_length=16)


    
class myuser1(models.Model):
  id=models.AutoField(primary_key=True)
  name=models.CharField(max_length=10)  
  password=models.CharField(max_length=16)

  def str(self):
      return self.name
        

  empAuth_objects=models.Manager()  

  class add_trainee(models.Model):
      id=models.AutoField(primary_key=True)
      trainee_name=models.CharField(max_length=10)  
      faculty=models.CharField(max_length=16)

class add_trainee1(models.Model):
      id=models.AutoField(primary_key=True)
      trainee_name=models.CharField(max_length=10)  
      faculty=models.CharField(max_length=16)      
      

class track(models.Model):
     id=models.AutoField(primary_key=True)
     track_name=models.CharField(max_length=10) 


class add_trainee2(models.Model):
      id=models.AutoField(primary_key=True)
      trainee_name=models.CharField(max_length=10)  
      faculty=models.CharField(max_length=16)      
      track=models.ForeignKey(track,on_delete=models.CASCADE) 

pages/views.py
from email import message
from multiprocessing import context
import re
from urllib import request
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import myuser1,track as track1,add_trainee2
from django.contrib.auth import authenticate,login as authlogin,logout as auth_logout
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User,auth

# Create your views here.

def home(request):
   return render(request,'pages/home.html')


def contact(request):
 return render(request,'pages/contact.html')


def about(request):
 return render(request,'pages/about.html')


def register(request):
    myuser11=myuser1()
    myuser12=User()
    context={};
    context['id']=1

    if(request.method=='POST') :
       name=request.POST['uname']
       password=request.POST['psw']
       myuser11.name=name
       myuser11.password=password
       User.objects.create_user(username=name,password=password,is_staff=True)

    myuser11.save()
   
    
    render(request,'pages/login.html')

    if myuser11.name=="" or myuser11.password=="":
     context['message']='empty feild'
    
     
    return render(request,'pages/register.html',context)  

def login(request):
   return render(request,'pages/login.html')

def checklogin(request):
   
   if request.method=='POST':
      username=request.POST['uname']
      passw=request.POST['psw']
      user=myuser1.empAuth_objects.all().filter(name=request.POST['uname'],password=request.POST['psw'])
      authuser=authenticate(request,username=username,password=passw)
      if(len(user)>0 and authuser is not None):
             request.session['uname']=request.POST['uname']
             authlogin(request,authuser)
             return redirect('home')
          
   else:
      return redirect(login)         

      
def logout(request):
         request.session.clear
         auth_logout(request)
         return render(request,'pages/login.html')





def addtrack(request):
   track11=track1()
   if(request.method=='POST') :
     context={};
     context['id']=1
     
     trackname=request.POST['trname']
     track11.track_name=trackname 
     track11.save()
   return render(request,'pages/addtrack.html')  




def addtrainee(request):
   track99=track1()
   trainee=add_trainee2()
   if(request.method=='POST') :
     context={};
     context['id']=1
     traineename=request.POST['traineeName']
     fac=request.POST['Fname']
     trac=request.POST['Tname']
     trainee.trainee_name=traineename
     trainee.faculty=fac
     trainee.track=track1.objects.get(id=request.POST['Tname'])
     trainee.save()
    
 
   return render(request,'pages/addtrainee.html')  

def index(request):
   trainees=add_trainee2.objects.all()
   return render(request,'pages/trainee.html',{'trainees':trainees})

def track111(request):
   track12=track1.objects.all()
   return render(request,'pages/track.html',{'tracks':track12})

def update(request,id):
     trainees=add_trainee2.objects.get(id=id)
     return render(request,'pages/update.html',{'trainees':trainees})

def actupdate(request,id):
   traineee=add_trainee2.objects.get(id=id)
   traineee.trainee_name=request.POST['trainee_name']
   traineee.faculty=request.POST['faculty']
   traineee.track=track1.objects.get(id=id)
   traineee.save()
   return redirect('/')


def dell(request,id):
     traineee=add_trainee2.objects.get(id=id)
     traineee.delete()
     return render(request,'pages/trainee.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default center">
  <div class="container-fluid">
  
    <ul class="nav navbar-nav">
      <li class="active"><a href="home">Home</a></li>
      <li><a href="about">about</a></li>
      <li><a href="contact">contact us</a></li>
      <li><a href="login">login</a></li>
      <li><a href="register">registeration</a></li>
      <li><a href="{% url 'logout'%}">logout</a></li>
      <li><a href="addtrack">addtrack</a></li>
      <li><a href="addtrainee">addtrainee</a></li>
      <li><a href="index">trainees</a></li>
      <li><a href="track111">tracks</a></li>
    </ul>
  </div>
</nav>
  


</body>
</html>

templates/pages/about.html
{% load static %}
<!DOCTYPE html>
<html>
<body>

  {% include 'base.html' %}
 

   <img src="{%static 'image/img.png'%}" alt="">

</body>
</html>

templates/pages/addtrack.html
{%include 'base.html'%}
   
<form method="POST">
    {% csrf_token %}  
<table class="center">
 
    
    <tr>
    <td><label><b>TRACK</b></label>
        <input type="text" placeholder="Enter track" name="trname" required></td>
      <td> <button type="submit">add track</button></td>

    </tr>
   
  </table>
  </form>

templates/pages/addtrainee.html
{%include 'base.html'%}
   
<form method="POST">
    {% csrf_token %}  
<table class="center">
<tr>
  <td><label><b>trainee name</b></label>
    <input type="text" placeholder="Enter trainee name" name="traineeName" required>
</td>
  <td><labe><b>faculty name</b></label>
    <input type="text" placeholder="Enter faculty name" name="Fname" required></td>
  <td><label><b>TRACK</b></label>
    <input type="text" placeholder="Enter track name" name="Tname" required></td>
    <td> <button type="submit">add trainee</button></td>
</tr>

</form>

templates/pages/contact.html
    {% include 'base.html' %}

  
        <h1>contact us</h1>
        <label for=fname>name</label><br>
        <input type="text" id="fname" name="fname" value="John"><br>
        <label for="lname">Last name:</label><br>
        <input type="text" id="lname" name="lname" value="Doe"><br><br>
        <input type="submit" value="Submit">
 

templates/pages/home.html
{%include 'base.html'%}
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1 {font-family: "Raleway", Arial, sans-serif}
h1 {letter-spacing: 6px}
.w3-row-padding img {margin-bottom: 12px}
</style>
<body>

<!-- !PAGE CONTENT! -->
<div class="w3-content" style="max-width:1500px">

<!-- Header -->
<header class="w3-panel w3-center w3-opacity" style="padding:128px 16px">
  <h1 class="w3-xlarge">{{request.session.uname}}</h1>

  </header>
  </div>
  </body>
  </html>

templates/pages/login.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
</head>
<body>

<h2>Login Form</h2>

<form action="{%url 'checklogin'%}" method="POST">
  
    {% csrf_token %}
  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
        
    <button type="submit">Login</button>
    
  </div>
  <div>
    {{msg}}
  </div>
<a href="register">register</a>
</form>

</body>
</html>

templates/pages/register.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
</head>
<body>
 
<h2>Registeration Form</h2>
{% block content %}

<form method="POST">
    {% csrf_token %}
  

  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
        
    <button type="submit">register</button>
   {{message}}
  </div>
  <a href="login">Login</a>

</form>
{% endblock %}
</body>
</html>

templates/pages/track.html
{%include 'base.html'%}

<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>


<table>
    

<tr>
<th>track id</th>
<th>track name</th>

</tr>

    {% for d in tracks %}
    <tr>
        <td>{{d.id}}</td>
        <td>{{d.track_name}}</td>
       
    </tr>
    {% endfor %}
</table>

</body>
</html>

templates/pages/trainee.html
{%include 'base.html'%}

<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>


<table>
    

<tr>
<th>track id</th>
<th>trainee name</th>
<th>faculty</th>
<th>track id</th>
</tr>

    {% for i in trainees %}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.trainee_name}}</td>
        <td>{{i.faculty}}</td>
        <td>{{i.track}}</td>
        <td><a href="/update/{{i.id}}">update</a></td>
        <td><a href="/dell/{{i.id}}">delete</a></td>
    </tr>
    {% endfor %}
</table>

</body>
</html>

templates/pages/update.html
{%include 'base.html'%}
   
<form method="POST" action="/actupdate/{{trainees.id}}">
    {% csrf_token %}  
<table class="center">
<tr>
  <td><label><b>trainee id</b></label>
    <input type="text" name= 'id' id='id_id' value="{{trainees.id}}" required>
</td>
  <td><labe><b>trainee name</b></label>
    <input type="text"  name="trainee_name" required  value="{{trainees.trainee_name}}"></td>
  <td><label><b>faculty</b></label>
    <input type="text"  name="faculty" required  value="{{trainees.faculty}}" ></td>
    <td><label><b>track id</b></label>
        <input type="text"  name="track" required  value="{{trainees.track}}" ></td>
    <td> <button type="submit">add trainee</button></td>
</tr>

</form>